FROM python:3.12-slim

WORKDIR /app

{{- if .UsePipenv }}
RUN pip install --no-cache-dir pipenv
COPY Pipfile Pipfile.lock* ./
RUN pipenv install --system --ignore-pipfile
{{- else }}
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
{{- end }}

COPY . .

EXPOSE 8000

CMD ["fastapi", "run", "app", "--port", "8000"]
