version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: fastapi-init
    binary: fastapi-init
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

archives:
  - id: fastapi-init
    name_template: "fastapi-init_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: markryangarcia
    name: fastapi-init
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
